### ISSUE TITLE
Update to Apex 22 and ORDS 22

### ISSUE THREAD

**Issue by geopicture** [MaikMichel/dockawex#7]
I really like this project. Could you please update to the newest versions? That would be great. Thanks a lot!

**Comment by MaikMichel** [comment]
Hi @geopicture, done ... so far... would you like to give it a try?

**Comment by geopicture** [comment]
It's working.

I've already tested with the newest version of ORDS:
export URL_ORDS=https://download.oracle.com/otn_software/java/ords/ords-22.2.0.172.1758.zip

Thanks for your brilliant work 👍
